CC = g++
CFLAGS = -std=c++17 -O3 -march=native -Wall -Wextra -Iinclude
LDFLAGS = -Lbuild -lmylib
OBJ = build/matrix.o

all: build/libmylib.a main benchmark

# Compile object files
build/matrix.o: src/matrix.cpp include/matrix.hpp
	$(CC) $(CFLAGS) -c src/matrix.cpp -o build/matrix.o

# Create Static Library
build/libmylib.a: build/matrix.o
	ar rcs $@ $^

# Compile main program
main: main.cpp build/matrix.o
	$(CC) $(CFLAGS) main.cpp build/matrix.o -o main

# Ensure benchmark recompiles when matrix changes
benchmark: benchmark.cpp build/libmylib.a
	$(CC) $(CFLAGS) benchmark.cpp $(LDFLAGS) -o benchmark

# Add dependency so `benchmark` runs correctly in one command
build/benchmark.o: benchmark.cpp
	$(CC) $(CFLAGS) -c benchmark.cpp -o build/benchmark.o

# Run
run: main
	./main

clean:
	rm -f build/*.o build/*.a main benchmark
